### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by morrisfranken** [Tomaat/CV2#1]
The reason for getting segfault is due to there being NaN values in the point-cloud.

These NaN values are introduced by Functions3D::depthToPointCloud for points where there is no depth-information or when the depth values exceed the threshold. The reason for adding these NaN values is such that an pcl::IntegralImageNormalEstimation function can be used to estimate the normals.

To solve it, you can use the following function to concatenate pointclouds:

```
void addPointCloud(pcl::PointCloud<pcl::PointNormal>::Ptr cloud_base, pcl::PointCloud<pcl::PointNormal>::Ptr cloud_add) {
    auto &v_base = cloud_base->points;
    auto &v_add  = cloud_add->points;
    v_base.reserve(v_base.size() + v_add.size());

    for(const auto &p : v_add) {
        if (!isnan(p.z))
            v_base.emplace_back(p);
    }
}
```

This however, will introduce another issue with saving the PCD, so I can recommend saving it as a PLY instead: `pcl::io::savePLYFile("../data/pointcloud.ply", *total_cloud);`

For creating a mesh I can recommend using pcl::Poisson, as this will create a smooth surface in contrast to the greedy approach. 

Good Luck!
~Morris

**Comment by DavidvanErkelens** [comment]
That fixed it, thanks!
